first pass at building an app image
yarn start:server

use service discovery name for rethinkdb

mess with travis

use https

mess with testing in travis

logs

curl

do a dang ol curl

CI/CD

deploy doesn't mean what i thought it did

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -6,17 +6,33 @@ services:
   - docker
 
 install:
-  - echo "install nothing!"
-
-script:
-  - echo "no tests!"
-
-after_success:
   - docker --version
   - uname -m
   - pip install --user awscli
+  - git clone https://github.com/the-bantam-breaks/website-automation.git
+  - docker network create bantam
+  - docker run -d --rm -p 28015:28015 -p 8090:8080 --name rethinkdb --network bantam -v $(pwd -P):/data rethinkdb
+
+script:
   - export PATH=$PATH:$HOME/.local/bin # put aws in the path
   - eval $(aws ecr get-login --region us-east-1 --no-include-email) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
   - docker build -t breaks-website:latest .
+  - docker run -d --rm --network bantam --name website -e RETHINKDB_HOST=rethinkdb -p 3000:3000 breaks-website:latest
+  - sleep 10
+  - |
+    STATUSCODE=$(curl -s -o /dev/null --write-out "%{http_code}" localhost:3000)
+    echo "build $TRAVIS_BUILD_NUMBER returned HTTP $STATUSCODE"
+    if [[ "$STATUSCODE" != 200 ]]; then
+      echo "Test HTTP request to website container failed!"
+      exit 1
+    fi
   - docker tag breaks-website:latest 796520576045.dkr.ecr.us-east-1.amazonaws.com/the-bantam-breaks/breaks-website:latest
+  - docker tag breaks-website:latest 796520576045.dkr.ecr.us-east-1.amazonaws.com/the-bantam-breaks/breaks-website:${TRAVIS_BUILD_NUMBER}
   - docker push 796520576045.dkr.ecr.us-east-1.amazonaws.com/the-bantam-breaks/breaks-website:latest
+  - docker push 796520576045.dkr.ecr.us-east-1.amazonaws.com/the-bantam-breaks/breaks-website:${TRAVIS_BUILD_NUMBER}
+
+after_success:
+  - echo "Build Successful!"
+  - docker logs website
+  - docker kill rethinkdb website
+  - ./cicd/deploy.sh $TRAVIS_BUILD_NUMBER
